version: '3'

services:
  rstudio:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: myERGM
    ports:
      - 8787:8787
    environment:
      - PASSWORD=${PASSWORD}
      - DISABLE_AUTH=true
      - USERID=${USERID}
      - GROUPID=${GROUPID}
      - ${PATH_TO_RSTUDIO_CONFIG}:/home/rstudio/.config/rstudio
      - ${RENV_PATHS_CACHE_HOST}:/home/rstudio/.local/share/renv/cache
    volumes:
      - ${PWD}:/home/rstudio/myergm
    tty: true
    stdin_open: true
